Repository f-lab-edu/careers, pull requests merged in 2021-06, with the labels that each got.

#22 Add 피드 기능 추가
  build.gradle
  src/main/java/com/dev/careers/annotation/LoginChecker.java
  src/main/java/com/dev/careers/aop/LoginCheckAop.java
  src/main/java/com/dev/careers/controller/CuratorController.java
  src/main/java/com/dev/careers/controller/FeedController.java
  src/main/java/com/dev/careers/controller/ProfileController.java
  src/main/java/com/dev/careers/mapper/FeedMapper.java
  src/main/java/com/dev/careers/model/Feed.java
  src/main/java/com/dev/careers/service/FeedService.java
  src/main/java/com/dev/careers/service/ProfileService.java
  src/main/resources/mybatis/FeedMapper.xml
  src/test/java/com/dev/careers/service/CuratorServiceTest.java
  src/test/java/com/dev/careers/service/FeedServiceTest.java
Labels: enhancement

#26 메인화면 피드 페이징 처리
  sql/ddl.sql
  src/main/java/com/dev/careers/controller/CuratorController.java
  src/main/java/com/dev/careers/controller/FeedController.java
  src/main/java/com/dev/careers/mapper/FeedMapper.java
  src/main/java/com/dev/careers/model/Curator.java
  src/main/java/com/dev/careers/model/Feed.java
  src/main/java/com/dev/careers/model/LoginParamter.java
  src/main/java/com/dev/careers/service/CuratorService.java
  src/main/java/com/dev/careers/service/FeedService.java
  src/main/java/com/dev/careers/service/error/CareersExceptionHandler.java
  src/main/java/com/dev/careers/service/error/CuratorExceptionHandler.java
  src/main/java/com/dev/careers/service/error/FailToSaveCuratorException.java
  src/main/java/com/dev/careers/service/error/FailToSaveFeedException.java
  src/main/java/com/dev/careers/service/error/SqlInsertException.java
  src/main/java/com/dev/careers/service/error/response/ResponseErrorMessage.java
  src/main/resources/mybatis/FeedMapper.xml
  src/test/java/com/dev/careers/controller/CuratorControllerTest.java
  src/test/java/com/dev/careers/service/CuratorServiceTest.java
  src/test/java/com/dev/careers/service/FeedServiceTest.java
Labels: enhancement

#29 Fix 프로필 잘못된 아이디 설정
  src/main/resources/mybatis/ProfileMapper.xml
Labels: bug

#30 댓글 기능 추가
  gradlew
  sql/ddl.sql
  src/main/java/com/dev/careers/controller/CommentController.java
  src/main/java/com/dev/careers/mapper/CommentMapper.java
  src/main/java/com/dev/careers/mapper/CuratorMapper.java
  src/main/java/com/dev/careers/model/Comment.java
  src/main/java/com/dev/careers/model/CommentList.java
  src/main/java/com/dev/careers/service/CommentService.java
  src/main/resources/mybatis/CommentMapper.xml
  src/test/java/com/dev/careers/service/CommentServiceTest.java
  src/test/java/com/dev/careers/service/CuratorServiceTest.java
Labels: enhancement

#34 CI/CD 반영
  Dockerfile
  Jenkinsfile-CD
  Jenkinsfile-CI
  checkstyle.gradle
  config/checkstyle/pre-commit
  sql/ddl.sql
  src/main/java/com/dev/careers/service/CuratorService.java
  src/main/java/com/dev/careers/service/encryption/Sha256Encryptor.java
  src/main/java/com/dev/careers/service/error/ViolationException.java
  src/main/java/com/dev/careers/service/session/SessionAuthenticator.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/test/java/com/dev/careers/service/CuratorServiceTest.java
Labels: enhancement

#35 ReadMe Update
  README.md
Labels: documentation
